# Generated by Django 5.2.11 on 2026-02-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='productquantity',
            unique_together={('product', 'unit_of_measure', 'package_type')},
        ),
        migrations.AddField(
            model_name='productquantity',
            name='age_groups',
            field=models.ManyToManyField(blank=True, related_name='product_quantities', to='ordering.agegroup'),
        ),
        migrations.RemoveField(
            model_name='productquantity',
            name='age_group',
        ),
    ]
