# Generated by Django 5.2.11 on 2026-02-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0002_agegroup_alter_productquantity_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='qty_package',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
