# Generated by Django 5.2.11 on 2026-02-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0003_orderproduct_qty_package_orderproduct_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='detail',
            field=models.TextField(blank=True, default=''),
        ),
    ]
