# Generated by Django 5.2.11 on 2026-02-18 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0004_orderproduct_detail'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productquantity',
            unique_together={('product', 'unit_of_measure', 'package_type', 'quantity')},
        ),
    ]
